export const IpcChannels = {
  Settings: {
    Get: 'settings:get',
    SetOpenRouterKey: 'settings:set-openrouter-key',
    HasOpenRouterKey: 'settings:has-openrouter-key',
    ClearOpenRouterKey: 'settings:clear-openrouter-key',
    SetDefaultModel: 'settings:set-default-model',
  },
  Projects: {
    CreateNew: 'projects:create-new',
    Open: 'projects:open',
    GetCurrent: 'projects:get-current',
    Close: 'projects:close',
    ListRecent: 'projects:list-recent',
  },
  Document: {
    Read: 'document:read',
    Write: 'document:write',
    Changed: 'document:changed',
  },
  Documents: {
    List: 'documents:list',
    Create: 'documents:create',
    Delete: 'documents:delete',
  },
  Chat: {
    Send: 'chat:send',
    History: 'chat:history',
    Clear: 'chat:clear',
    Started: 'chat:started',
    Chunk: 'chat:chunk',
    ChunkDone: 'chat:chunk-done',
  },
  Comments: {
    List: 'comments:list',
    Create: 'comments:create',
    Delete: 'comments:delete',
    Changed: 'comments:changed',
  },
  PendingEdits: {
    List: 'pending-edits:list',
    Accept: 'pending-edits:accept',
    Reject: 'pending-edits:reject',
    Patch: 'pending-edits:patch',
    Clear: 'pending-edits:clear',
    Changed: 'pending-edits:changed',
  },
  Sources: {
    Ingest: 'sources:ingest',
    IngestText: 'sources:ingest-text',
    PickFiles: 'sources:pick-files',
    List: 'sources:list',
    Read: 'sources:read',
    Delete: 'sources:delete',
    Changed: 'sources:changed',
  },
} as const;
